src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting stores the name of countries.</description>
    <label>Country</label>
</CustomObject>

src/objects/Jade_Country__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Jade_Country</label>
</CustomObject>

src/objects/Jade_State__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>country__c</fullName>
        <label>country</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Jade_State</label>
</CustomObject>

src/classes/Jade_ContactDetails.cls
public with sharing class Jade_ContactDetails {

    public Contact contact {get; set;}
    public list<SelectOption> stateOptions {get; set;}
    
    public Jade_ContactDetails() {
        contact = new Contact();
    }
    
    public list<SelectOption> getCountryOptions() {
    
        set<String> countries = Jade_Country__c.getAll().keySet();
        list<SelectOption> countryOptions = new list<SelectOption>{new SelectOption('--SELECT--', '--SELECT--')};
        for (String country : countries) {
            countryOptions.add(new SelectOption(country, country));
        }
        return countryOptions;
    }
    
    public Pagereference action() {
        system.debug('===@@@@==='+contact.Country__c);
        Map<String, Jade_State__c> stateMap = Jade_State__c.getAll();
        stateOptions = new list<SelectOption>{new SelectOption('--SELECT--','--SELECT--')};
        
        for(Jade_State__c state : stateMap.values()) {
            
            if (contact.Country__c != '--SELECT--' && state.country__c != null && state.country__c.equals(contact.Country__c)) {
                stateOptions.add(new SelectOption(state.Name, state.Name));
            }
            
        }
    
        system.debug('==stateOptions===='+stateOptions);
        return null;
    }
    
    public Pagereference cancel() {
       

       
       return new Pagereference('003/o');
    }
    
    public Pagereference save() {
       
       Database.saveresult sr = Database.insert(contact);
       
       return new Pagereference('/'+sr.getId());
    }



}